Repository exactpro/docs-toolkit, pull requests merged in 2023-06, with the labels that each got.

#5 Update README.md
  README.md
Labels: documentation

#17 12 Add configuration for search console authorization meta tags
  app.config.ts
  components/ep/PageMeta.vue
  docs/app.config.ts
  pages/[...slug].vue
Labels: enhancement

#29 Basic meta tags customization
  app.vue
  components/ep/PageMeta.vue
  docs/app.config.ts
  nuxt.schema.ts
Labels: enhancement, seo

#30 CSS styles for pdf print
  assets/css/prose.css
  layouts/docs.vue
  pages/[...slug].vue
  tailwind.config.js
Labels: enhancement

#8 add sitemap to repository
  nuxt.config.ts
  nuxt.schema.ts
  package-lock.json
  package.json
  server/routes/sitemap.xml.ts
Labels: enhancement

#31 [DO-565] GitHub buttons hotfix
  components/ep/layout/GithubActions.vue
  server/routes/api/_docs-toolkit/github/edit-base-path.ts
  server/routes/api/terms/check-partial.ts
Labels: bug

#37 [DO-567] Change logic of setting ToC
  composables/states.ts
  composables/table-of-contents.ts
  pages/[...slug].vue
Labels: bug
