Repository exactpro/docs-toolkit, pull requests merged in 2023-07, with the labels that each got.

#41 [DO-575] No config autocomplete for globally declared types
  modules/docs-toolkit-config.ts
  nuxt.schema.ts
Labels: bug

#43 [DO-578] Declare default config correctly
  app.config.ts
  nuxt.schema.ts
Labels: bug

#44 [DO-550] SEO features documentation
  docs/content/2.features/5.seo.md
Labels: documentation

#49 [DO-563] Implement open graph protocol meta tags customization
  app.vue
  components/ep/PageMeta.vue
  composables/config.ts
  docs/app.config.ts
  docs/content/2.features/5.seo.md
  nuxt.schema.ts
  server/routes/robots.txt.ts
  server/routes/sitemap.xml.ts
Labels: enhancement
